invoice_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import hello_world

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', hello_world),
    path('', include('invoices.urls', namespace='invoices')),
]

# urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Invoice test admin system"
admin.site.index_title = "Management"

invoices/urls.py
from .views import (InvoiceListView,InvoiceFormView,SimpleTemplateView,InvoiceUpdateView,
                    AddPositionsFormView,CloseInvoiceView,InvoicePositionDeleteView,invoice_pdf_view)
from django.urls import path
app_name = 'invoices'

urlpatterns =[
    path('',InvoiceListView.as_view(),name='main'),
    path('new/',InvoiceFormView.as_view(),name="create"),
    # path('<pk>/',SimpleTemplateView.as_view(),name='simple-template'),
    path('<pk>/',AddPositionsFormView.as_view(),name='detail'),
    path('<pk>/update/',InvoiceUpdateView.as_view(),name='update'),
    path('<pk>/delete/<int:position_pk>/',InvoicePositionDeleteView.as_view(),name='position-delete'),
    path('<pk>/pdf/', invoice_pdf_view, name="pdf"),
    path('<pk>/close/',CloseInvoiceView.as_view(),name='close'),


]

invoices/models.py
from django.db import models
from profiles.models import Profile
from receivers.models import Receiver
# Create your models here.


class Tag(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return str(self.name)

class Invoice(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    receiver = models.ForeignKey(Receiver, on_delete=models.CASCADE)
    number = models.CharField(max_length=150)
    completion_date = models.DateField()
    issue_date = models.DateField()
    payment_date = models.DateField()
    created = models.DateTimeField(auto_now_add=True)
    # if closed - hide add positions and unable adding new ones
    closed = models.BooleanField(default=False)
    # for educational purposes only:
    tags = models.ManyToManyField(Tag, blank=True)

    def __str__(self):
        return f"Invoice number: {self.number}, pk: {self.pk}"

    @property
    def tags(self):
        return self.tags.all()

    @property
    def positions(self):
        return self.position_set.all()

    @property
    def total_amount(self):
        total = 0
        qs = self.positions
        for pos in qs:
            total += pos.amount
        return total

invoices/forms.py
from django import forms
from .models import Invoice
from django.core.exceptions import ValidationError

class InvoiceForm(forms.ModelForm):
    completion_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    issue_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    payment_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    class Meta:
        model = Invoice
        fields = (
            'receiver','number','completion_date','issue_date','payment_date',
        )
        # labels={
        #     'receiver' :'test1',
        #     'number':'test2',
        # }

    def clean_number(self):
        number = self.cleaned_data.get('number')
        if len(number)<10:
            raise ValidationError('Number is tooo short ')
        return number

invoices/views.py
from django.shortcuts import render,get_object_or_404
from django.views.generic import (ListView,FormView,TemplateView,DetailView,UpdateView,RedirectView,DeleteView)
from django.urls import reverse_lazy,reverse
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin

# xhtml2pdf
import os
from django.conf import settings
from django.http import HttpResponse
from django.template.loader import get_template
from xhtml2pdf import pisa
from django.contrib.staticfiles import finders
# Create your views here.
from positions.forms import PositionForm
from positions.models import Position

from . models import Invoice
from  profiles.models import Profile
from .forms import InvoiceForm
from .mixins import InvoiceNotClosedMixin

class InvoiceListView(LoginRequiredMixin,ListView):
    model = Invoice
    template_name = "invoices/main.html" #default invoice_list 
    paginate_by = 3
    context_object_name = 'qs'

    def get_queryset(self):
        print(self.request.user)
        # profile = Profile.objects.get(Profile,user=self.request.user)
        profile = get_object_or_404(Profile,user=self.request.user)
        # qs = Invoice.objects.filter(profile=profile).order_by('-created')
        # return qs
        return super().get_queryset().filter(profile=profile).order_by('-created')

class InvoiceFormView(LoginRequiredMixin,FormView):
    form_class = InvoiceForm
    template_name = "invoices/create.html"
    # success_url = reverse_lazy('invoices:main')

    i_instance = None

    def get_success_url(self):
        return reverse('invoices:detail',kwargs={'pk':self.i_instance.pk})

    def form_valid(self, form):
        profile = Profile.objects.get(user=self.request.user)
        instance = form.save(commit=False)
        instance.profile = profile
        form.save()
        self.i_instance = instance
        return super().form_valid(form)

class SimpleTemplateView(LoginRequiredMixin,DetailView):
    model = Invoice
    template_name = 'invoices/simple_template.html'

# class SimpleTemplateView(TemplateView):
#     template_name = 'invoices/simple_template.html'

class InvoiceUpdateView(LoginRequiredMixin,InvoiceNotClosedMixin,UpdateView):
    model = Invoice
    template_name = 'invoices/update.html'
    form_class = InvoiceForm
    success_url = reverse_lazy('invoices:main')

    def form_valid(self, form):
        instance = form.save()
        messages.info(self.request,f'Succesfully updated invoice -{instance.number}')
        return super().form_valid(form)

class AddPositionsFormView(LoginRequiredMixin,FormView):
    form_class = PositionForm
    template_name = 'invoices/detail.html'

    def get_success_url(self):
        return self.request.path

    def form_valid(self,form):
        invoice_pk = self.kwargs.get('pk')
        invoice_obj = Invoice.objects.get(pk=invoice_pk)
        instance = form.save(commit=False)
        instance.invoice = invoice_obj
        form.save()
        messages.info(self.request,f"Succesfully added position ={instance.title}")
        return super().form_valid(form) 

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        invoice_obj = Invoice.objects.get(pk=self.kwargs.get('pk'))
        qs = invoice_obj.positions
        context['obj']=invoice_obj
        context['qs'] = qs
        return context

class CloseInvoiceView(LoginRequiredMixin,RedirectView):
    pattern_name = "invoices:detail"
    print("inside CloseInvoiceView")

    def get_redirect_url(self,*args,**kwargs):
        pk = self.kwargs.get('pk')
        obj = Invoice.objects.get(pk=pk)
        obj.closed=True
        print("before save CloseInvoiceView")
        print(obj.closed)
        obj.save()
        print("after save CloseInvoiceView")
        return super().get_redirect_url(*args,**kwargs)

class InvoicePositionDeleteView(InvoiceNotClosedMixin,DeleteView):
    model = Position
    template_name= 'invoices/position_confirm_delete.html'

    def get_object(self):
        pk = self.kwargs.get('position_pk')
        obj = Position.objects.get(pk=pk)
        return obj

    def get_success_url(self):
        messages.info(self.request,f'Deleted position -{self.object.title}')
        return reverse('invoices:detail',kwargs={'pk':self.object.invoice.id})

def invoice_pdf_view(request,**kwargs):
    pk = kwargs.get('pk')
    obj = Invoice.objects.get(pk=pk)

    logo_result = finders.find('img/logo.png')
    font_result = finders.find('font/Lato-Regular.ttf') 

    searched_locations = finders.searched_locations
    print(searched_locations)

    template_path ='invoices/pdf.html' 
    context = {
        'object':obj,
        'static':{
            'font':font_result,
            'logo':logo_result,
        },
    }

    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'filename="invoice.pdf"' 
    template = get_template(template_path)
    html = template.render(context)

    # create a pdf 
    pisa_status = pisa.CreatePDF(
        html.encode('utf-8'),dest = response,encoding='utf-8')
    
    if pisa_status.err:
        return HttpResponse('we had some error in creating pdf' +html+'</prev>')
    return response

invoices/templates/invoices/create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}create{% endblock title %}
{% block content %}
    <form action=""method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary mt-3">Save</button>
    </form>
{% endblock content %}

invoices/templates/invoices/detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    detailpage
{% endblock title %}
{% block content %}

    <!--add positions Modal -->
    <div class="modal fade" id="addPositionsModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">At positions</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form action=""method="POST">
                    {% csrf_token %}
                    {{form|crispy}}
                    <button type="submit" class="btn btn-primary mt-3">save</button>
                </form>
            </div>
            
        </div>
        </div>
    </div>
    <!--close Invoice Modal -->
    <div class="modal fade" id="closeInvoiceModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Are you sure you want to close the invoice ?
            </div>
            <div class="modal-footer">
            <a href="{% url 'invoices:close' obj.pk %}" class="btn btn-secondary">Close</a>
            </div>
        </div>
        </div>
    </div>
    
    <div>
        {% if not obj.closed %}
            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#addPositionsModal">
                + add positions
            </button>
            <button type="button" class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#closeInvoiceModal">
                close
            </button>
        {% else %}
            <a href="pdf"><div class="btn btn-danger">pdf</div></a>
        {% endif %}
    </div>

    {% if messages %}
        {% for message in messages %}
            
            {% if message.tags == "info" %}
                <div class="alert alert-primary mt-2">{{message}}</div>
            {% endif %}
                
        {% endfor %}
    {% endif %}

    <div class="mt-3">
        <h5>Receiver: {{obj.receiver.name}}</h5>
        <hr>
        <h3>Positions</h3>
        
        {% if qs %}
        <table class="table">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">title</th>
                <th scope="col">description</th>
                <th scope="col">amount</th>
                <th scope="col">delete</th>
              </tr>
            </thead>
            <tbody>
                {% for item in qs %}
                    <tr style="vertical-align: middle;">
                    <th scope="row">{{forloop.counter}}</th>
                    <td>{{item.title}}</td>
                    <td>{{item.description}}</td>
                    <td>${{item.amount}}</td>
                    <td>
                        {% if not obj.closed %}
                            <a href="{% url 'invoices:position-delete' obj.pk item.pk %}" class="btn btn-danger">X</a>
                        {% else %}
                            closed
                        {% endif %}
                    </td>
                    </tr>
                
                {% endfor %}
             
            </tbody>
          </table>
          <div class="mt-2 text-end">
              <h2>Total amount : ${{obj.total_amount}}</h2>
          </div>
        {% else %}
            <h5>No position added ..</h5>
        {% endif %}
            
    </div>
{% endblock content %}

invoices/templates/invoices/main.html
{% extends 'base.html' %}

{% block title %}{% endblock title %}


{% block content %}
    
    {% if messages %}
        {% for message in messages %}
            
            {% if message.tags == "info" %}
                <div class="alert alert-primary mt-2">{{message}}</div>
            {% endif %}
                
        {% endfor %}
    {% endif %}
        


    {% if qs %}
        {% for obj in qs %}
            <div class="card mb-2" style="width: 100%;">
                <div class="card-body">
                    <h5 class="card-title">{{obj.number}}-{{obj.receiver.name}}</h5>
                    <div class="card-text">{{obj.completion_date}}</div>
                    <div class="text-muted">{{obj.total_amount}}</div>
                    <div class="mt-2">
                        <a href="{% url 'invoices:detail' obj.pk %}" class="btn btn-primary">details</a>
                        
                        {% if not obj.closed %}
                            <a href="{% url 'invoices:update' obj.pk %}" class="btn btn-info">Update</a>
                        {% endif %}
                            
                    </div>
                </div>
            </div>
        {% endfor %}
    {% else %}
            <h3>No invoices ..</h3>
    {% endif %}
    {% if is_paginated %}
            <nav aria-label="invoice pagination">
                <ul class="pagination">
                <li class="page-item {% if page_obj.has_previous %} {% else %} disabled {% endif %}">
                    <a 
                    {% if page_obj.has_previous %}
                        href="?page={{ page_obj.previous_page_number}}"
                    {% endif %} class="page-link" tabindex="-1">Previous</a>
                </li>
                
                {% for i in paginator.page_range %}
                    <li class="page-item {%if page_obj.number == i %} active {% endif %}">
                        <a class="page-link" href="?page={{i}}">{{i}}</a>
                    </li>
                {% endfor %}
            
                <li class="page-item {% if page_obj.has_next %} {% else %} disabled {% endif %}">
                    <a {% if page_obj.has_next %}
                            href="?page={{ page_obj.next_page_number}}"
                        {% endif %} class="page-link" >Next</a>
                </li>
                </ul>
            </nav>
            
    {% endif %}
        
{% endblock content %}
    

invoices/templates/invoices/pdf.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Invoice pdf</title>
    <style>
        @page{
            size:a4 portrait;
            margin:2cm;
        }
        @font-face {
            font-family:'Lato';
            src:url({{static.font}});
        }
        * {
            font-family: 'Lato';
            font-size:12px;
        }
        table{
            border-collapse:collapse;
            border:1px solid blue;
            padding:5px;
        }
    </style>
</head>
<body>
    <section id="header-section">
        <table style="width:100%;border 0px">
            <tr>
                <th style="text-align:left;width:25%">
                    <img src="static/img/logo.png" alt="" width="150">
                </th>
                <th style="text-align:right">
                    <br>
                    <div style="font-size:18px">Invoice Number{{object.number}}</div>
                    Completion date: {{object.completion_date}} <br>
                    Issue date : {{object.issue_date}} <br>
                    Payment date : {{object.payment_date}} <br>
                    <div>account number: {{object.profile.account_number}} </div>
                </th>
            </tr>
        </table>
        <hr>
        <br>
        <table style="width:100%">
            <th style="text-align:left">
                <div style="font-size:15px">Seller :</div>
                {{object.profile.company_name}}
            </th>
            <th style="text-align:left">
                <div style="font-size:15px">Receiver :</div>
                {{object.receiver.name}} <br>
                {{object.receiver.address}} <br>
                {{object.receiver.website}}<br>
            </th>
        </table>
    </section>
    <br>
    <section id="data-section">
        
        {% if object.positions %}
            <h3>Positions</h3>
            <table style="width: 100%">
                <tr style="background-color:yellow">
                    <th style="text-align:left;width:5%">#</th>
                    <th style="text-align:left;">Title</th>
                    <th style="text-align:left">Description</th>
                    <th style="text-align:left">Amount</th>
                </tr>
                
                {% for position in object.positions %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{position.title}}</td>
                        <td>{{position.description}}</td>
                        <td>${{position.amount}}</td>
                    </tr>
                    
                {% endfor %}
                    
            </table>
            {% else %}
            <h3>No positions added</h3>
        {% endif %}
        <div style="font-size:15px;margin-top:10px;text-align:right">Table: ${{object.total_amount}}</div>
    </section>
    
</body>
</html>

invoices/templates/invoices/position_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
    delete position
{% endblock title %}

{% block content %}
    <form action=""method="POST" >
        {% csrf_token %}
        <p>Are you sure you want to delete "<b>{{object.title}}</b>"</p>
        <button type="submit" class="btn btn-primary">Delete</button>
    </form>

{% endblock content %}

invoices/templates/invoices/simple_template.html
{% extends 'base.html' %}

{% block title %}home{% endblock title %}
{% block content %}
    {{object.pk}} - {{object.number}}
    
{% endblock content %}

invoices/templates/invoices/update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Update
{% endblock title %}

{% block content %}
    <form action=""method="POST">
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit" class="ctn btn-primary mt-2">Update</button>
    </form>
{% endblock content %}