invoice_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import hello_world

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', hello_world),
    path('', include('invoices.urls', namespace='invoices')),
]

# urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Invoice test admin system"
admin.site.index_title = "Management"

invoices/urls.py
from .views import (InvoiceListView,InvoiceFormView,SimpleTemplateView,InvoiceUpdateView,
                    AddPositionsFormView,CloseInvoiceView,InvoicePositionDeleteView,invoice_pdf_view)
from django.urls import path
app_name = 'invoices'

urlpatterns =[
    path('',InvoiceListView.as_view(),name='main'),
    path('new/',InvoiceFormView.as_view(),name="create"),
    # path('<pk>/',SimpleTemplateView.as_view(),name='simple-template'),
    path('<pk>/',AddPositionsFormView.as_view(),name='detail'),
    path('<pk>/update/',InvoiceUpdateView.as_view(),name='update'),
    path('<pk>/delete/<int:position_pk>/',InvoicePositionDeleteView.as_view(),name='position-delete'),
    path('<pk>/pdf/', invoice_pdf_view, name="pdf"),
    path('<pk>/close/',CloseInvoiceView.as_view(),name='close'),


]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- favicon -->
    <link
      rel="shortcut icon"
      type="image/png"
      href="{% static 'favicon.ico' %}"
    />

    <!-- Bootstrap CSS -->
    
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'style.css' %}" />

    {% block scripts %} {% endblock scripts %}

    <title>Invoice app | {% block title %}{% endblock title %}</title>
  </head>
  <body>
    {% include 'navbar.html' %}
    <div class="container mt-3">{% block content %} {% endblock content %}</div>

    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
      integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
      integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block scripts %}{% endblock scripts %}

{% block title %}Hello world{% endblock title %}

{% block content %}Inside content - {{obj_.number}}{% endblock content %}

templates/navbar.html
<nav class="navbar navbar-dark bg-primary">
    <div class="container">
      <a href="{% url 'invoices:main' %}" class="navbar-brand">Invoice app</a>
      <a href="{% url 'invoices:create' %}" class="btn btn-outline-light">+ New</a>
    </div>
</nav>